language: c

os:
  - linux
  - osx
    osx_image: xcode7.3
  - osx
    osx_image: xcode8.1

compiler:
  - clang
  - gcc

#matrix:
#  include:
#    - os: osx
#      osx_image: xcode7.3


install: 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install pkg-config libusb-1.0-0-dev ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libusb gawk; fi


#sudo apt-get -y install make gcc g++ pkg-config libusb-1.0-0-dev

script: ./config.sh && make
